#!/usr/bin/env node
// Build a study: slides/*.mjs -> build/<name>.excalidraw (all frames),
// build/slides/NN-<id>.excalidraw (one frame each), manifest.json, outline.md.
// Usage: node build.mjs [studyDir]
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { Slide } from "./lib/kit.mjs";
import { buildContext, loadConfig, loadSlides, outPaths, resolveStudyDir, studyMetrics, validateSpecs } from "./lib/project.mjs";
import { getMetrics, setMetrics } from "./lib/text.mjs";
import { sceneFile } from "./lib/scene.mjs";
import { isMain } from "./lib/main.mjs";

export const GENERATOR = "excalidraw-study 0.1.0";

function sha(value) {
  return crypto.createHash("sha256").update(value).digest("hex");
}

function mdCell(v) {
  return String(v ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
}

export async function buildStudy(dirArg, { quiet = false } = {}) {
  const dir = resolveStudyDir(dirArg);
  const loaded = await loadConfig(dir);
  const { config, theme } = loaded;
  const defs = await loadSlides(dir, theme);
  if (defs.length === 0) throw new Error("no slides found in slides/");
  const specErrors = validateSpecs(defs, loaded);
  if (specErrors.length) throw new Error(`slide spec errors:\n  ${specErrors.join("\n  ")}`);
  const ctx = buildContext(loaded, defs);
  setMetrics(studyMetrics(config, outPaths(dir, config)));

  const slides = defs.map((d, i) => {
    const s = new Slide(ctx, d.spec, i);
    try {
      d.draw(s, ctx);
      s.finish();
    } catch (e) {
      e.message = `slides/${d.file} ${d.spec.id}: ${e.message}`;
      throw e;
    }
    return { def: d, slide: s };
  });

  const p = outPaths(dir, config);
  fs.mkdirSync(p.slidesDir, { recursive: true });
  const allElements = slides.flatMap(({ slide }) => slide.elements);
  const background = theme.colors.white;
  fs.writeFileSync(p.combined, `${JSON.stringify(sceneFile(allElements, { background }), null, 2)}\n`);

  const keep = new Set();
  const entries = slides.map(({ def, slide }) => {
    const file = `${slide.nn}-${def.spec.id}.excalidraw`;
    keep.add(file);
    fs.writeFileSync(path.join(p.slidesDir, file), `${JSON.stringify(sceneFile(slide.elements, { background }), null, 2)}\n`);
    const texts = slide.elements.filter((e) => e.type === "text").map((e) => e.text).join("\n");
    const { spec } = def;
    return {
      number: slide.number,
      id: spec.id,
      frameId: slide.frameId,
      title: spec.title,
      subtitle: spec.subtitle ?? "",
      takeaway: spec.takeaway ?? "",
      left: spec.left ?? "",
      part: spec.part ?? null,
      step: spec.step ?? null,
      kind: spec.kind ?? null,
      chrome: spec.chrome ?? "full",
      source: spec.source ?? "",
      claims: spec.claims ?? [],
      terms: spec.terms ?? [],
      lint: spec.lint ?? null,
      module: `slides/${def.file}`,
      file: path.relative(dir, path.join(p.slidesDir, file)),
      elements: slide.elements.length,
      textSha256: sha(texts),
      bodyBottom: slide.bodyBottom,
      barY: slide.barY ?? null,
    };
  });
  for (const f of fs.readdirSync(p.slidesDir)) {
    if (f.endsWith(".excalidraw") && !keep.has(f)) fs.unlinkSync(path.join(p.slidesDir, f));
  }

  const manifest = {
    generator: GENERATOR,
    name: config.name,
    title: config.title ?? config.name,
    lang: config.lang,
    combined: path.relative(dir, p.combined),
    canvas: theme.canvas,
    layout: theme.layout,
    steps: loaded.steps.map((s) => s.name),
    count: entries.length,
    metrics: getMetrics(),
    slides: entries,
  };
  fs.writeFileSync(p.manifest, `${JSON.stringify(manifest, null, 2)}\n`);

  const partLabel = (id) => {
    const part = config.parts[id];
    return part ? `${part.label}${part.topic ? ` · ${part.topic}` : ""}` : "";
  };
  const outline = [
    `# ${config.title ?? config.name} outline`,
    "",
    `Generated by build.mjs from slides/. ${entries.length} slides.`,
    "",
    "| # | id | part | step | kind | title | takeaway | claims |",
    "|---|---|---|---|---|---|---|---|",
    ...entries.map((e) => `| ${e.number} | ${e.id} | ${mdCell(partLabel(e.part))} | ${mdCell(e.step)} | ${mdCell(e.kind)} | ${mdCell(e.title)} | ${mdCell(e.takeaway)} | ${mdCell(e.claims.join(", "))} |`),
    "",
  ].join("\n");
  fs.writeFileSync(p.outline, outline);

  if (!quiet) {
    console.log(`built ${entries.length} slides, ${allElements.length} elements`);
    console.log(`  ${path.relative(process.cwd(), p.combined) || p.combined}`);
    console.log(`  ${path.relative(process.cwd(), p.manifest) || p.manifest}`);
  }
  return { dir, config, theme, manifest, paths: p };
}

if (isMain(import.meta.url)) {
  buildStudy(process.argv[2]).catch((e) => {
    console.error(`build failed: ${e.message}`);
    process.exit(1);
  });
}
